1

diff --git a/.github/workflows/k8s-setup-init.yml b/.github/workflows/k8s-setup-init.yml
--- a/.github/workflows/k8s-setup-init.yml
+++ b/.github/workflows/k8s-setup-init.yml
@@ -25,32 +25,18 @@ on:
         type: string
         default: 'mycluster'
 
-      skip_file:
-        description: 'Skip OFFLINE file download'
+      metricsserver_enable:
+        description: 'Enable Metrics Server'
         required: true
         default: true
         type: boolean
 
-      skip_image:
-        description: 'Skip OFFLINE images sync'
+      metallb_enable:
+        description: 'Enable MetalLB'
         required: true
         default: true
         type: boolean
 
-      vm_user:
-        description: 'VM Guest: OS User'
-        required: true
-        default: vagrant
-        type: choice
-        options:
-          - vagrant
-          - root
-
-      VMs:
-        description: 'VM list JSON array'
-        required: true
-        type: string
-        default: '["10.10.10.11","10.10.10.12","10.10.10.13", "10.10.10.101", "10.10.10.102"]'
 
       # k8s_version:
       #   description: 'supported stable k8s version https://kubernetes.io/releases/'
@@ -66,6 +52,7 @@ on:
 env:
   TAILSCALE_HOST: pve
   TAILSCALE_NET: taile80cb.ts.net
+  GHPROXY: https://ghfast.top/
   # VM_TEMPLATE_ID: 2009 # vm模板的ID
   # VM_CIDR: 10.10.10 # vmbr0 vmbr1 的网段
   # MASTER_IP: 10.10.10.11
@@ -91,41 +78,41 @@ jobs:
       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       # - uses: actions/checkout@v5
 
-      # # 1️⃣ 安装基础依赖
-      # - name: Install OS base packages
-      #   run: |
-      #     missing_pkgs=()
-      #     # package -> command mapping
-      #     declare -A pkg_cmd=(
-      #       [skopeo]=skopeo
-      #       [python3]=python3
-      #       [python3-pip]=pip3
-      #       [python3-venv]=python3
-      #       [jq]=jq
-      #     )
+      # 1️⃣ 安装基础依赖
+      - name: Install OS base packages
+        run: |
+          missing_pkgs=()
+          # package -> command mapping
+          declare -A pkg_cmd=(
+            [skopeo]=skopeo
+            [python3]=python3
+            [python3-pip]=pip3
+            [python3-venv]=python3
+            [jq]=jq
+          )
 
-      #     for pkg in skopeo python3 python3-pip python3-venv jq; do
-      #       cmd="${pkg_cmd[$pkg]}"
-      #       if ! command -v "$cmd" >/dev/null 2>&1; then
-      #         missing_pkgs+=("$pkg")
-      #       fi
-      #     done
+          for pkg in skopeo python3 python3-pip python3-venv jq; do
+            cmd="${pkg_cmd[$pkg]}"
+            if ! command -v "$cmd" >/dev/null 2>&1; then
+              missing_pkgs+=("$pkg")
+            fi
+          done
 
-      #     if [ ${#missing_pkgs[@]} -gt 0 ]; then
-      #       echo "Installing missing packages: ${missing_pkgs[*]}"
-      #       sudo apt-get update -yq >/dev/null
-      #       sudo apt-get install -yq "${missing_pkgs[@]}" >/dev/null
-      #     else
-      #       echo "All required commands already exist."
-      #     fi
+          if [ ${#missing_pkgs[@]} -gt 0 ]; then
+            echo "Installing missing packages: ${missing_pkgs[*]}"
+            sudo apt-get update -yq >/dev/null
+            sudo apt-get install -yq "${missing_pkgs[@]}" >/dev/null
+          else
+            echo "All required commands already exist."
+          fi
 
-      #     # # externally-managed-environment 错误的临时解决方法，后续可以改为在 runner 上正确设置 Python 环境
-      #     sudo rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED
+          # # externally-managed-environment 错误的临时解决方法，后续可以改为在 runner 上正确设置 Python 环境
+          sudo rm -rf /usr/lib/python3.*/EXTERNALLY-MANAGED
 
-      #     if ! command -v yq >/dev/null 2>&1; then
-      #       wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
-      #       sudo install -m 755 yq_linux_amd64 /usr/bin/yq
-      #     fi          
+          if ! command -v yq >/dev/null 2>&1; then
+            wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
+            sudo install -m 755 yq_linux_amd64 /usr/bin/yq
+          fi          
 
       # 2️⃣ 检查 tailscale SSH 免密状态
       - name: Check if already ssh key-based
@@ -152,13 +139,34 @@ jobs:
           version: latest # https://pkgs.tailscale.com/stable/#static
           use-cache: 'true'
 
-      # 4️⃣ kubectl
-      - name: kubectl
+      # 4️⃣ metrics-server
+      - name: metrics-server
         run: |
+          # 1. 在runner上下载 metrics-server 的 components.yaml，并且修改启动参数，添加 --kubelet-insecure-tls
+          temp_dir=$(mktemp -d) || { echo "创建临时目录失败"; exit 1; }
+          trap 'rm -rf "$temp_dir"; echo "清理临时目录: $temp_dir"' EXIT
+          echo "临时目录路径: $temp_dir"
+          cd $temp_dir
+          wget -c https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
+          sed -i '/metric-resolution=/a\        - --kubelet-insecure-tls # 加上该启动参数' components.yaml
+          image=$(awk '/image:/ {print $2}' components.yaml)
+          echo "### skopeo copy docker://${image} docker://${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:5000/k8s/${image#*/}"
+          skopeo copy docker://${image} docker://${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:5000/k8s/${image#*/}
+          sed -i "s#${image}#${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:5000/k8s/${image#*/}#g" components.yaml
+
+
+          # 2. rsync到pve上
+          rsync -e 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' -avz --partial --progress --inplace components.yaml root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }}:/root/
+
+          # 3. 到pve上执行
           ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@${{ env.TAILSCALE_HOST }}.${{ env.TAILSCALE_NET }} << 'EOF'
           source ~/.bashrc
           export KUBECONFIG=~/.kube/${{ github.event.inputs.K8S_CLUSTER_NAME }}.kubeconfig
           kubectl get nodes -o wide
+
+          cd /root
+          # kubectl apply -f components.yaml
+          
           EOF
 
       # # 5️⃣ 下载 kubespray 仓库，并复制 sample inventory 作为基础
